### ISSUE TITLE
what the meaning of Dx and offs?

### ISSUE THREAD

**Issue by woxihuanchirou** [iqiukp/SVDD-MATLAB#1]
In the line 38-46 of svdd_train.m,
`Dx = - 2*sum( (ones(size(I,1),1)*alf_SV').*K_SV, 2); 
offs = 1 + sum(sum((alf_SV *alf_SV').*computeKernelMatrix(ker,SV,SV)));`
For SV, we have: R² = ||φ(xi)-a||² = K<x,x> - 2∑α*K<x,xi> + α‘*Q*α, (Q is Kernel Matrix)
but I dont konw what the meaning of Dx and offset.
Does Dx equal to - 2∑α*K<x,xi> and offs equal to R² ?
And what for 1 in offs?

**Comment by iqiukp** [comment]
Sorry to reply to this issue now. A description of the calculation of the radius has been added to the updated version of the code.
